---

- hosts: test-1

  tasks:

  - name: create the file to be used for swap
    command: fallocate -l 4G /mnt/4GB.swap

  - name: format the file for swap
    command: mkswap /mnt/4GB.swap

  - name: change swap file permissions
    file: path=/mnt/4GB.swap owner=root group=root mode=0600

  - name: add the file to the system as a swap file
    command: swapon /mnt/4GB.swap

  - name: write swap entry in fstab
    mount: name=none src=/mnt/4GB.swap fstype=swap opts=sw passno=0 dump=0 state=present
